# Generated by Django 3.2.13 on 2022-06-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigs',
            name='category',
            field=models.CharField(choices=[('PC', 'Pest Control'), ('HC', 'Home Cleaners'), ('GL', 'Gardening and Landscaping'), ('LS', 'LockSmith'), ('EL', 'Electricians'), ('PL', 'Plumbing'), ('MO', 'Moving'), ('CO', 'Contractors'), ('OT', 'Others')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
